version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: client-fl:v26

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: server-fl:v20
